<?php
declare(strict_types=1);

// Ziptastic SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ZiptasticUtility::setRegistrar(function (ZiptasticUtility $u): void {
    $u->clean = [ZiptasticClean::class, 'call'];
    $u->done = [ZiptasticDone::class, 'call'];
    $u->make_error = [ZiptasticMakeError::class, 'call'];
    $u->feature_add = [ZiptasticFeatureAdd::class, 'call'];
    $u->feature_hook = [ZiptasticFeatureHook::class, 'call'];
    $u->feature_init = [ZiptasticFeatureInit::class, 'call'];
    $u->fetcher = [ZiptasticFetcher::class, 'call'];
    $u->make_fetch_def = [ZiptasticMakeFetchDef::class, 'call'];
    $u->make_context = [ZiptasticMakeContext::class, 'call'];
    $u->make_options = [ZiptasticMakeOptions::class, 'call'];
    $u->make_request = [ZiptasticMakeRequest::class, 'call'];
    $u->make_response = [ZiptasticMakeResponse::class, 'call'];
    $u->make_result = [ZiptasticMakeResult::class, 'call'];
    $u->make_point = [ZiptasticMakePoint::class, 'call'];
    $u->make_spec = [ZiptasticMakeSpec::class, 'call'];
    $u->make_url = [ZiptasticMakeUrl::class, 'call'];
    $u->param = [ZiptasticParam::class, 'call'];
    $u->prepare_auth = [ZiptasticPrepareAuth::class, 'call'];
    $u->prepare_body = [ZiptasticPrepareBody::class, 'call'];
    $u->prepare_headers = [ZiptasticPrepareHeaders::class, 'call'];
    $u->prepare_method = [ZiptasticPrepareMethod::class, 'call'];
    $u->prepare_params = [ZiptasticPrepareParams::class, 'call'];
    $u->prepare_path = [ZiptasticPreparePath::class, 'call'];
    $u->prepare_query = [ZiptasticPrepareQuery::class, 'call'];
    $u->graphql_body = [ZiptasticGraphql::class, 'body'];
    $u->graphql_errors = [ZiptasticGraphql::class, 'errors'];
    $u->result_basic = [ZiptasticResultBasic::class, 'call'];
    $u->result_body = [ZiptasticResultBody::class, 'call'];
    $u->result_headers = [ZiptasticResultHeaders::class, 'call'];
    $u->transform_request = [ZiptasticTransformRequest::class, 'call'];
    $u->transform_response = [ZiptasticTransformResponse::class, 'call'];
});
